# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
# app/config/config.yml

liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        avatar:
            quality: 75
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound

        avatarmedium:
            quality: 75
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound

        vignette:
            quality: 75
            filters:
                thumbnail:
                    size: [250, 500]
                    mode: outbound

        avatarsmall:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        news:
            quality: 75
            filters:
                thumbnail:
                    size: [1500, 400]
                    mode: outbound

        news_page:
            quality: 75
            filters:
                thumbnail:
                    size: [1920, 1080]
                    mode: outbound

        news_admin:
            quality: 75
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: inset
                    allow_upscale: true

        illustration_page:
            quality: 75

        illustration_index:
            quality: 75
            filters:
                thumbnail:
                    size: [1920, 1080]
                    mode: outbound
                    allow_upscale: true
                    downscale:
                        max: [1920, 1080]
