vich_uploader:
    db_driver: orm

    mappings:
        users_avatar_image:
            uri_prefix: /media/users/avatar
            upload_destination: '%kernel.project_dir%/public/media/users/avatar'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        news_image:
          uri_prefix: /media/news
          upload_destination: '%kernel.project_dir%/public/media/news'
          namer: Vich\UploaderBundle\Naming\UniqidNamer

        recruitments_image:
            uri_prefix: /media/recruitments
            upload_destination: '%kernel.project_dir%/public/media/recruitments'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        illumanga_image:
          uri_prefix: /media/illustrations
          upload_destination: '%kernel.project_dir%/public/media/illustrations'
          namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
